@api_HostAddress = http://localhost:5287

POST {{api_HostAddress}}/clientes/3/transacoes
Content-Type: application/json

{"valor": 1.2, "tipo": "d", "descricao": "devolve"}

###

GET {{api_HostAddress}}/clientes/3/extrato
Accept: application/json

###

POST {{api_HostAddress}}/clientes/3/transacoes
Content-Type: application/json

{"valor": 1, "tipo": "d", "descricao": "devolve"}

###

POST {{api_HostAddress}}/clientes/3/transacoes
Content-Type: application/json

{"valor": 1, "tipo": "d", "descricao": "devolve"}

###
POST {{api_HostAddress}}/clientes/3/transacoes
Content-Type: application/json

{"valor": 1, "tipo": "c", "descricao": "toma"}