FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-jammy-aot AS build
ARG TARGETARCH
WORKDIR /source
EXPOSE 80

# copy csproj and restore as distinct layers
COPY ["api/api.csproj", "api/"]
COPY ["api/nuget.config", "api/"]
RUN dotnet restore "api/api.csproj" -r linux-$TARGETARCH

# copy and publish app and libraries
COPY . .
RUN dotnet publish "api/api.csproj" -r linux-$TARGETARCH  -o /app
RUN rm /app/*.dbg /app/*.Development.json

# final stage/image
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-aot
WORKDIR /app
COPY --from=build /app .
USER $APP_UID
ENTRYPOINT ["./api"]

##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################


FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-jammy-aot AS build
ARG TARGETARCH
WORKDIR /source
EXPOSE 80

# copy csproj and restore as distinct layers
COPY ["api/api.csproj", "api/"]
COPY ["api/nuget.config", "api/"]
RUN dotnet restore "api/api.csproj" -r linux-$TARGETARCH

# copy and publish app and libraries
COPY . .
RUN dotnet publish "api/api.csproj" -r linux-$TARGETARCH  -o /app
RUN rm /app/*.dbg /app/*.Development.json

# final stage/image
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-aot
WORKDIR /app
COPY --from=build /app .
USER $APP_UID
ENTRYPOINT ["./api"]